server:
  port: 8080
  servlet:
    context-path: /cms

spring:
  application:
    name: card-management-system
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=card_management}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Fraud Detection Service Configuration
fraud:
  service:
    url: ${FRAUD_SERVICE_URL:http://localhost:8081}

# Logging
logging:
  level:
    com.fintech: DEBUG
    org.springframework.web: DEBUG
    feign: DEBUG