server:
  port: 8081
  servlet:
    context-path: /fds

spring:
  application:
    name: fraud-detection-service
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=fraud_detection}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Fraud Detection Configuration
fraud:
  detection:
    amount-limit: 10000.00
    frequency-limit: 8
    time-interval-hours: 1

# Springdoc OpenAPI configuration
springdoc:
  swagger-ui:
    path: /fds/swagger-ui.html

# Logging
logging:
  level:
    com.fraud: DEBUG
    org.drools: DEBUG
    org.springframework.web: DEBUG 